import { Pod, EquipmentStatus, MachineStates } from "../interfaces";

export const mockData: { pods: Pod[] } = {
  pods: [
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 30",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.SESSAO,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.TURN_OFF,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.DELAY_SESSAO,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.PRE_SESSAO,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.PRE_SESSAO,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.SESSAO_LIMPEZA,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
    {
      id: "dae12e-e21e1-e12e12e-e12e12e",
      name: "Sala 31",
      model: "Void One",
      serialNumber: "123123123",
      ipAddress: "123123",
      hostname: "123123",
      connection: {
        isConnected: true,
        status: EquipmentStatus.OK,
      },
      screen: {
        actualTemperature: 34,
        actualTime: "10:20",
        cooler: true,
        rpmCooler: 30,
        remainingTime: "10:20",
        sessionStatus: MachineStates.SESSAO_NOTURNO,
        status: "OK",
        fwVersion: "1.0.1",
        finalMusicFile: "Music 1",
        initialMusicFile: "Music 1",
        discEquipStatus: EquipmentStatus.OK,
        serverEquipStatus: EquipmentStatus.OK,
        systemEquipStatus: EquipmentStatus.OK,
      },
    },
  ],
};
